name: print-env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo workspace: ${GITHUB_WORKSPACE}
        echo sha: ${GITHUB_SHA}
        echo ref: ${GITHUB_REF}
    - name: Get changed files
      id: getfiles
      run: |
        echo "::Set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{github.sha}} | xargs)"
    - name: Print changed files
      run: |
        echo ${{ steps.getfiles.outputs.files }}
